const money = value => Number(value).toFixed(2);
let cart = JSON.parse(localStorage.getItem('cart')) || [];
let wishlist = JSON.parse(localStorage.getItem('wishlist')) || [];
let activeCategory = new URLSearchParams(location.search).get('category') || 'all';
let searchTerm = '';
let sortMode = 'default';

function saveState(){localStorage.setItem('cart',JSON.stringify(cart));localStorage.setItem('wishlist',JSON.stringify(wishlist));}
function updateCartCount(){const count=cart.reduce((sum,item)=>sum+item.qty,0);$('#cartCount').text(count);}
function productImage(p){return `${p.image}?auto=format&fit=crop&w=700&q=80`;}
function stars(rating){return `<span class="rating"><i class="fa-solid fa-star"></i> ${rating}</span>`;}
function cardTemplate(p){const liked=wishlist.includes(p.id);return `<article class="product-card"><img src="${productImage(p)}" alt="${p.name}"><div class="product-info"><div class="product-meta"><small>${p.category.toUpperCase()}</small>${stars(p.rating)}</div><h3>${p.name}</h3><p>${p.description}</p><div class="product-meta"><span class="price">$${money(p.price)}</span><button class="quick-view" data-id="${p.id}">View</button></div><div class="product-actions"><button class="add-cart" data-id="${p.id}">Add to Cart</button><button class="wishlist" data-id="${p.id}"><i class="fa-${liked?'solid':'regular'} fa-heart"></i></button></div></div></article>`;}
function getFilteredProducts(){let list=[...PRODUCTS];if(activeCategory!=='all') list=list.filter(p=>p.category===activeCategory);if(searchTerm) list=list.filter(p=>p.name.toLowerCase().includes(searchTerm)||p.description.toLowerCase().includes(searchTerm));if(sortMode==='low') list.sort((a,b)=>a.price-b.price);if(sortMode==='high') list.sort((a,b)=>b.price-a.price);if(sortMode==='rating') list.sort((a,b)=>b.rating-a.rating);return list;}
function renderProducts(){const list=getFilteredProducts();$('#productGrid').html(list.map(cardTemplate).join('')||'<div class="empty">No products found.</div>');$('#productCount').text(`${list.length} product(s) found`);$('.filter').removeClass('active');$(`.filter[data-category="${activeCategory}"]`).addClass('active');}
function renderFeatured(){const featured=PRODUCTS.slice(0,4);$('#featuredProducts').html(featured.map(cardTemplate).join(''));}
function addToCart(id){const product=PRODUCTS.find(p=>p.id===id);const existing=cart.find(i=>i.id===id);if(existing){existing.qty+=1}else{cart.push({...product,qty:1})}saveState();updateCartCount();showToast(`${product.name} added to cart`);}
function showToast(message){const toast=$(`<div class="toast">${message}</div>`).appendTo('body');toast.css({position:'fixed',right:'20px',bottom:'20px',background:'var(--primary)',color:'var(--bg)',padding:'14px 18px',borderRadius:'999px',zIndex:999});setTimeout(()=>toast.fadeOut(250,()=>toast.remove()),1800);}
function renderCartPage(){if(!$('#cartItems').length)return;if(cart.length===0){$('#cartItems').html('<div class="empty">Your cart is empty.</div>');$('#subtotal,#tax,#total').text('0.00');return;}$('#cartItems').html(cart.map(item=>`<div class="cart-item"><img src="${productImage(item)}" alt="${item.name}"><div><h3>${item.name}</h3><p>$${money(item.price)} each</p></div><div class="qty"><button class="dec" data-id="${item.id}">-</button><strong>${item.qty}</strong><button class="inc" data-id="${item.id}">+</button><button class="remove-item" data-id="${item.id}">Remove</button></div></div>`).join(''));const subtotal=cart.reduce((s,i)=>s+i.price*i.qty,0);const tax=subtotal*.08;$('#subtotal').text(money(subtotal));$('#tax').text(money(tax));$('#total').text(money(subtotal+tax));}
function openModal(id){const p=PRODUCTS.find(x=>x.id===id);$('#modalBody').html(`<div class="modal-product"><img src="${productImage(p)}" alt="${p.name}"><div><span class="badge">${p.category}</span><h2>${p.name}</h2><p>${p.description}</p><p>${stars(p.rating)}</p><h2>$${money(p.price)}</h2><button class="btn primary add-cart" data-id="${p.id}">Add to Cart</button></div></div>`);$('#productModal').fadeIn(150);}
function applyTheme(){const theme=localStorage.getItem('theme')||'light';document.documentElement.setAttribute('data-theme',theme);$('#themeToggle i').attr('class',theme==='dark'?'fa-solid fa-sun':'fa-solid fa-moon');}
$(document).ready(function(){applyTheme();updateCartCount();renderFeatured();renderProducts();renderCartPage();$('#menuBtn').on('click',()=>$('#navMenu').toggleClass('show'));$('#themeToggle').on('click',()=>{const next=document.documentElement.getAttribute('data-theme')==='dark'?'light':'dark';localStorage.setItem('theme',next);applyTheme();});$(document).on('click','.add-cart',function(){addToCart(Number($(this).data('id')));renderCartPage();});$(document).on('click','.wishlist',function(){const id=Number($(this).data('id'));wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];saveState();renderProducts();renderFeatured();});$(document).on('click','.quick-view',function(){openModal(Number($(this).data('id')));});$('#closeModal,#productModal').on('click',function(e){if(e.target.id==='productModal'||e.target.id==='closeModal')$('#productModal').fadeOut(150);});$('.filter').on('click',function(){activeCategory=$(this).data('category');renderProducts();});$('#searchInput').on('input',function(){searchTerm=$(this).val().toLowerCase();renderProducts();});$('#sortSelect').on('change',function(){sortMode=$(this).val();renderProducts();});$(document).on('click','.inc',function(){cart.find(i=>i.id===Number($(this).data('id'))).qty++;saveState();updateCartCount();renderCartPage();});$(document).on('click','.dec',function(){const item=cart.find(i=>i.id===Number($(this).data('id')));item.qty--;if(item.qty<=0)cart=cart.filter(i=>i.id!==item.id);saveState();updateCartCount();renderCartPage();});$(document).on('click','.remove-item',function(){cart=cart.filter(i=>i.id!==Number($(this).data('id')));saveState();updateCartCount();renderCartPage();});$('#checkoutBtn').on('click',function(){if(cart.length===0){alert('Your cart is empty.');return;}alert('Replace this with Stripe, PayPal, or Shopify checkout link.');});});
